package pe.edu.upn.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import pe.edu.upn.entity.Carrera;
import pe.edu.upn.entity.Estudiante;
import pe.edu.upn.entity.Facultad;
import pe.edu.upn.entity.Genero;

public class EstudianteJFrame extends javax.swing.JFrame {

    private List<Estudiante> estudiantes;
    
    public EstudianteJFrame() {
        initComponents();
        this.estudiantes = new ArrayList<>();
        this.loadEstudiantes();
        this.loadTabla();
        
    }
    private void loadEstudiantes() {
        Facultad facultad = new Facultad("Ingenieria");
        Carrera carrera = new Carrera("Ingenieria de Sistemas", facultad);
        Estudiante estu1 = new Estudiante("20190101", carrera, "74859632", "Chura", "Jazmine", 
                Genero.FEMENINO, null);
        Estudiante estu2 = new Estudiante("20190102", carrera, "78965412", "Morales", "Zahira", 
                Genero.FEMENINO, null);
        Estudiante estu3 = new Estudiante("20190103", carrera, "74857855", "Benavides", "Ruth", 
                Genero.FEMENINO, null);
        Estudiante estu4 = new Estudiante("20190104", carrera, "78954532", "Prado", "Maribel", 
                Genero.FEMENINO, null);
        this.estudiantes.add(estu1);
        this.estudiantes.add(estu2);
        this.estudiantes.add(estu3);
        this.estudiantes.add(estu4);
    }
    public void loadTabla() {
        int tamano = this.estudiantes.size();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setRowCount( tamano );
        // Estableciendo las columnas
        modelo.addColumn("Id");
        modelo.addColumn("Codigo");
        modelo.addColumn("Dni");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Nombres");
        // Setting data
        for(int i=0; i<tamano; i++) {
            Estudiante estu = estudiantes.get(i);
            modelo.setValueAt(estu.getId(), i, 0);
            modelo.setValueAt(estu.getCodigo(), i, 1);
            modelo.setValueAt(estu.getDni(), i, 2);
            modelo.setValueAt(estu.getApellidos(), i, 3);
            modelo.setValueAt(estu.getNombres(), i, 4);
        }
        this.tblEstudiante.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstudiante = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de matricula");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("CRUD de Estudiantes");

        tblEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEstudiante);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnEditar)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        EstudianteNewJFrame newFrame = new EstudianteNewJFrame();
        newFrame.setFrmLista(this);
        newFrame.setEstudiantes(estudiantes);
        newFrame.setVisible(true);
                
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        int row = tblEstudiante.getSelectedRow();
        if (row != -1) {
            int id = (int)tblEstudiante.getValueAt(row, 0);
        
            EstudianteEditJFrame editFrame = new EstudianteEditJFrame();
            editFrame.setFrmLista(this);
            editFrame.setEstudiantes(estudiantes);   
            editFrame.setId(id);
            editFrame.setVisible(true);
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudianteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudianteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudianteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudianteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudianteJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEstudiante;
    // End of variables declaration//GEN-END:variables
}
